package gophengine

var IntroText [][]string = [][]string{
	[]string{"ultimate rhythmgaming", "probably"},
	[]string{"dope ass game", "playstation magazine"},
	[]string{"dancin", "forever"},
	[]string{"funkin", "forever"},
	[]string{"rhythm gaming", "ultimate"},
	[]string{"game of the year", "forever"},
	[]string{"you already know", "we really out here"},
	[]string{"like parappa", "but cooler"},
	[]string{"better than geometry dash", "fight me robtop"},
	[]string{"women are real", "this is official"},
	[]string{"Hatsune Miku", "biggest inspiration"},
	[]string{"too many people", "my head hurts"},
	[]string{"refined taste in music", "if i say so myself"},
	[]string{"never forget to", "pray to god"},
	[]string{"dababy", "biggest inspiration"},
	[]string{"fashionably late", "but here it is"},
	[]string{"yooooooooooo", "yooooooooo"},
	[]string{"pico funny", "pico funny"},
	[]string{"github exclusive intro text", "open source forever"},
	[]string{"boyfriend rocks", "daddy dearest sucks"},
	[]string{"slovenskooooo", "slovenskooooo"},
	[]string{"ruuzombeerok", "bum bum bum bum bum bum"},
	[]string{"na orave dobre", "na orave zdravo"},
	[]string{"boyfriend", "is the goat"},
	[]string{"daddy dearest", "is debil"},
	[]string{"boyfriend", "je goat"},
	[]string{"daddy dearest", "je kkt"},
	[]string{"daddy dearest", "je debil"},
	[]string{"dont code in rust", "we only golang"},
	[]string{"package main", "import fmt"},
	[]string{"segmentation fault", "core dumped"},
}
